services:
  redis:
    image: redis:7.4-rc2
    ports:
      - 6379:6379
  app:
    build: 
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 80:80
    working_dir: /app

