services:
  redis:
    image: redis:7.4-rc2
    restart: always
    volumes:
      - redis_data:/data
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app:rw
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 80:80
    working_dir: /app

volumes:
  redis_data:
